modelService:
  name: model-service
  image: ghcr.io/remla2025-team10/model-service:latest
  canaryImage: ghcr.io/remla2025-team10/model-service:v0.0.5
  port: 3000
  pvSize: 3Gi

appService:
  name: app-service
  image: ghcr.io/remla2025-team10/app-service:latest
  canaryImage: ghcr.io/remla2025-team10/app-service:beta
  port: 8080

ingress:
  enabled: true
  host: ""

serviceMonitor:
  enabled: true
  create: true
  namespace: "default"  
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: myprom

prometheusRule:
  additionalLabels:
    release: myprom

alertmanager:
  receiverEmail: alerts.remla.team10@gmail.com

grafana:
  dashboardsConfigMaps:
    sentiment-dashboard: "sentiment-dashboard"
  additionalDataSources: []