---
- name: Finalizing Cluster Setup
  hosts: all
  become: true
  tasks:
    ########## Install MetalLB ##########
    - name: Copy MetalLB to VM
      copy:
        src: ansible/files/metallb-native.yaml
        dest: /tmp/metallb-native.yaml
        mode: '0644'

    - name: Install MetalLB
      become_user: vagrant
      shell: kubectl apply -f /tmp/metallb-native.yaml

    - name: Add IPAddressPool
      copy:
        dest: /etc/kubernetes/ip-address-pool.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: ip-address-pool
            namespace: metallb-system
          spec:
            addresses:
            - 192.168.56.90-192.168.56.99
    
    - name: Apply IPAddressPool
      become_user: vagrant
      shell: |
        kubectl apply -f /etc/kubernetes/ip-address-pool.yaml
    
    - name: Configure L2Advertisement
      copy:
        dest: /etc/kubernetes/l2-advertisement.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advertisement
            namespace: metallb-system

    - name: Apply L2Advertisement
      become_user: vagrant
      shell:
        kubectl apply -f /etc/kubernetes/l2-advertisement.yaml

    - name: Wait for MetalLB
      become_user: vagrant
      shell: |
        kubectl wait -n metallb-system -l app=metallb,component=controller --for=condition=ready pod --timeout=60s

    ######### Install Nginx Ingress ##########
    - name: Add Helm repository
      become_user: vagrant
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    
    - name: Install Nginx Ingress Controller
      become_user: vagrant
      kubernetes.core.helm:
        name: nginx-ingress
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          controller:
            service:
              loadBalancerIP: 192.168.56.90
    ####### Install Kubernetes Dashboard #######
    - name: Add Kubernetes Dashboard repository
      become_user: vagrant
      shell: |
        helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
    - name: Install Kubernetes Dashboard
      become_user: vagrant
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true

    - name: Copy Dashboard Manifest to VM
      copy:
        src: kubernetes-dashboard/dashboard-adminuser.yaml
        dest: /tmp/dashboard-adminuser.yaml
        mode: '0644'
      
    - name: Create Admin User
      become_user: vagrant
      shell: kubectl apply -f /tmp/dashboard-adminuser.yaml
    
    - name: Copy Ingress Dashboard to VM
      copy:
        src: kubernetes-dashboard/ingress-dashboard.yaml
        dest: /tmp/ingress-dashboard.yaml
        mode: '0644'
    
    - name: Apply Ingress Dashboard
      become_user: vagrant
      shell: kubectl apply -f /tmp/ingress-dashboard.yaml

    - name: Copy Ingress App to VM
      copy:
        src: app-ingress/app-ingress.yaml
        dest: /tmp/app-ingress.yaml
        mode: '0644'

    - name: Apply Ingress App
      become_user: vagrant
      shell: kubectl apply -f /tmp/app-ingress.yaml

    - name: Deploy services
      copy:
        src: deployment.yaml
        dest: /tmp/deployment.yaml
        mode: '0644'

    - name: Apply Deployment
      become_user: vagrant
      shell: kubectl apply -f /tmp/deployment.yaml