apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Release.Name }}-alerts
  namespace: {{ .Release.Name }}
  labels:
    alertmanagerConfig: "model-stack"
spec:
  route:
    receiver: {{ .Release.Name }}-email-alert
  receivers:
    - name: {{ .Release.Name }}-email-alert
      emailConfigs:
        - smarthost: smtp.gmail.com:587
          to: {{ .Values.alertmanager.receiverEmail }}
          sendResolved: true
          from: {{ .Values.alertmanager.senderEmail }}
          authUsername: {{ .Values.alertmanager.senderEmail }}
          authPassword:
            name: {{ .Values.alertmanager.smtpSecret.name }}
            key: {{ .Values.alertmanager.smtpSecret.key }}