apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: team10-alerts
  namespace: default
spec:
  route:
    receiver: email-alert
  receivers:
    - name: email-alert
      emailConfigs:
        - smarthost: smtp.gmail.com:587
          to: {{ .Values.alertmanager.receiverEmail }}
          sendResolved: true
          from: alerts.remla.team10@gmail.com
          authUsername: alerts.remla.team10@gmail.com
          authPassword:
            name: smtp-password-secret
            key: smtp_password