apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: "{{ .Release.Name }}-alerts"
  namespace: {{ .Release.Namespace }}
  labels:
    alertmanagerConfig: {{ .Values.alert.discoveryLabel }}
spec:
  route:
    matchers:
    - name: release
      value: "{{ .Release.Name }}"
    receiver: "{{ .Release.Name }}-email-alert"
    groupBy: ['alertname']
    groupWait: 10s 
    groupInterval: 1m
    repeatInterval: 1m
    continue: true
  receivers:
    - name: "{{ .Release.Name }}-email-alert"
      emailConfigs:
        - smarthost: smtp.gmail.com:587
          to: {{ .Values.alert.receiverEmail }}
          from: {{ .Values.alert.senderEmail }}
          authUsername: {{ .Values.alert.senderEmail }}
          authPassword:
            name: {{ .Values.alert.smtpSecret.name }}
            key: {{ .Values.alert.smtpSecret.key }}
          sendResolved: True
