{{- if .Values.rateLimiting.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Release.Name }}-rate-limiting
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway # applied to Istio ingress gateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY # apply to the gateway context
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket: # rate limit (local) configured in values.yaml
                max_tokens: {{ .Values.rateLimiting.requestsPerMin }}
                tokens_per_fill: 10
                fill_interval: 60s # every minute
              filter_enabled:
                runtime_key: local_rate_limit
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
{{- end}}
