# templates/pods.yaml
{{- $ms := .Values.modelService -}}
{{- $as := .Values.appService -}}

---
# model-service v1 (stable)
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ $ms.name }}-v1
  labels:
    app: {{ .Release.Name }}-{{ $ms.name }}
    version: v1
spec:
  containers:
    - name: {{ $ms.name }}
      image: {{ $ms.image }}
      ports:
        - containerPort: {{ $ms.port }}
      env:
        - name: PORT
          value: "{{ $ms.port }}"
      volumeMounts:
        - name: {{ .Release.Name }}-model-volume
          mountPath: /model-service/models
  volumes:
    - name: {{ .Release.Name }}-model-volume
      hostPath:
        path: ./
        type: Directory

---
# model-service v2 (canary)
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ $ms.name }}-v2
  labels:
    app: {{ .Release.Name }}-{{ $ms.name }}
    version: v2
spec:
  containers:
    - name: {{ $ms.name }}
      image: {{ $ms.canaryImage }}
      ports:
        - containerPort: {{ $ms.port }}
      env:
        - name: PORT
          value: "{{ $ms.port }}"
      volumeMounts:
        - name: {{ .Release.Name }}-model-volume
          mountPath: /model-service/models
  volumes:
    - name: {{ .Release.Name }}-model-volume
      hostPath:
        path: ./
        type: Directory

---
# app-service v1 (stable)
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ $as.name }}-v1
  labels:
    app: {{ .Release.Name }}-{{ $as.name }}
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ $as.port }}"
spec:
  containers:
    - name: {{ $as.name }}
      image: {{ $as.image }}
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: {{ $as.port }}
      env:
        - name: PORT
          value: "{{ $as.port }}"
        - name: MODEL_SERVICE_URL
          value: "http://{{ .Release.Name }}-{{ $ms.name }}:{{ $ms.port }}"

---
# app-service v2 (canary)
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ $as.name }}-v2
  labels:
    app: {{ .Release.Name }}-{{ $as.name }}
    version: v2
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ $as.port }}"
spec:
  containers:
    - name: {{ $as.name }}
      image: {{ $as.canaryImage }}
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: {{ $as.port }}
      env:
        - name: PORT
          value: "{{ $as.port }}"
        - name: MODEL_SERVICE_URL
          value: "http://{{ .Release.Name }}-{{ $ms.name }}:{{ $ms.port }}"
