apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-request-rate-alert
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.prometheusRule.additionalLabels.release }}
spec:
  groups:
    - name: request-rate.rules
      rules:
        - alert: RequestsPerMinute
          expr: sum(rate(flask_http_request_total[1m]) * 60) > 15
          for: 2m
          labels:
            severity: warning
            release: {{ .Release.Name }}
          annotations:
            summary: ">15 requests per minute for 2 minutes"
        - alert: ApplicationTestAlert
          # This expression sums the total number of Flask HTTP requests for this specific
          # Helm release's app-service. It will fire when the total count is > 2 (i.e., 3 or more).
          expr: sum(flask_http_request_total) > 93
          # 'for: 0s' makes the alert fire instantly once the condition is met.
          for: 0s
          labels:
            # It MUST have the release label to be routed correctly by Alertmanager.
            severity: critical # Make it stand out from normal alerts.
            release: "{{ .Release.Name }}"
          annotations:
            summary: "Test alert triggered for {{ .Release.Name }}"
            description: "This is a test to confirm the alerting pipeline is working correctly for the {{ .Release.Name }} application."