{{- $ms := .Values.modelService -}}
{{- $as := .Values.appService -}}

---
# Istio VirtualService for Prometheus
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-prometheus-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - "prometheus.local"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.serviceMonitor.additionalLabels.release }}-kube-prometheus-sta-prometheus.monitoring.svc.cluster.local
            port:
              number: 9090

---
# Istio VirtualService for Kiali
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-kiali-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - "kiali.local"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001

---
# Istio VirtualService for Grafana
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-grafana-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - "grafana.local"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana.istio-system.svc.cluster.local
            port:
              number: 3000

---
# Istio VirtualService for app-service
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-app-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - "app.local"
  http:
    - match:
        - headers:
            x-user:
              exact: "experiment"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ $as.name }}
            subset: v2
          weight: 100
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ $as.name }}
            subset: v1
          weight: 90
        - destination:
            host: {{ .Release.Name }}-{{ $as.name }}
            subset: v2
          weight: 10

---
# Istio VirtualService for model-service consistency
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-model-service-vs
spec:
  hosts:
    - {{ .Release.Name }}-{{ $ms.name }}
  http:
    - match:
        - sourceLabels:
            version: v2
      route:
        - destination:
            host: {{ .Release.Name }}-{{ $ms.name }}
            subset: v2
    - route:
        - destination:
            host: {{ .Release.Name }}-{{ $ms.name }}
            subset: v1