modelService:
  name: model-service
  image: ghcr.io/remla2025-team10/model-service:v0.0.5
  port: 3000

appService:
  name: app-service
  image: ghcr.io/remla2025-team10/app-service:latest
  port: 8080
  modelServiceUrl: http://{{ .Release.Name }}-model-service:3000

ingress:
  enabled: true
  host: ""

serviceMonitor:
  enabled: true
  namespace: "default"  
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: myprom