modelService:
  name: model-service
  image: ghcr.io/remla2025-team10/model-service:latest
  port: 3000
  pvSize: 3Gi

appService:
  name: app-service
  image: ghcr.io/remla2025-team10/app-service:latest
  port: 8080

ingress:
  enabled: true
  host: ""

serviceMonitor:
  enabled: true
  namespace: "default"  
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: myprom
alertmanager:
  receiverEmail: alerts.remla.team10@gmail.com