{{- $ms := .Values.modelService -}}
{{- $as := .Values.appService -}}

---
# Istio DestinationRule for model-service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ $ms.name }}-dr
spec:
  host: {{ .Release.Name }}-{{ $ms.name }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

---
# Istio DestinationRule for app-service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ $as.name }}-dr
spec:
  host: {{ .Release.Name }}-{{ $as.name }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-user
