apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-model-pv
spec:
  capacity:
    storage: {{ .Values.modelService.pvSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/shared/models