apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.modelService.name }}
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.appService.name }}
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-stack.fullname" . }}-app-service
  labels:
    {{- include "model-stack.labels" . | nindent 4 }}
    app: {{ include "model-stack.fullname" . }}-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000  # metrics port
      targetPort: 8000
      protocol: TCP
      name: metrics  # referred to in the ServiceMonitor
  selector:
    app: {{ .Release.Name }}-{{ .Values.appService.name }}