apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: always-firing-test-2
  namespace: default
  labels:
    release: myprom
spec:
  groups:
    - name: always-firing.rules
      rules:
        - alert: BrandNewAlert
          expr: vector(1)
          for: 15s