apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: always-firing-test
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
    - name: always-firing.rules
      rules:
        - alert: AlwaysFiringTestAlert
          expr: vector(1)