---
- hosts: ctrl
  become: true
  tasks:

    ########### 1.2 Set up KB controller  ###########

    # Step 13: Init cluster

    - name: (Step 13) Check if the cluster is already initalized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: (Step 13) Initialize the KB cluster
      shell: |
        kubeadm init \
          --apiserver-advertise-address=192.168.56.100 \
          --node-name ctrl \
          --pod-network-cidr=10.244.0.0/16
      when: not kubeconfig.stat.exists

    # Step 14: Setup kubectl

    - name: (Step 14) Create .kube directory for vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'
    
    - name: (Step 14) Copy admin kubeconfig to vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: (Step 14) Copy kubeconfig to shared folder for host access
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /vagrant/admin.conf
        remote_src: yes

    # Step 15: Create pod network
    - name: Copy kube-flannel to remote host
      copy:
        src: files/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
        mode: '0644'

    - name: Apply Flannel network plugin
      command: kubectl apply -f /tmp/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    # Step 16: Install Helm
    - name: Add Helm GPG signing key
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm apt repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm-stable

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Helm
      apt:
        name: helm
        state: present

    # Step 17: Install Helm-Diff
    - name: Install helm-diff plugin
      become: yes
      become_user: vagrant
      shell: |
        helm plugin list | grep diff || helm plugin install https://github.com/databus23/helm-diff
      args:
        executable: /bin/bash
      environment:
        HELM_PLUGINS: /home/vagrant/.local/share/helm/plugins