---
- hosts: node-*
  become: true
  tasks: 
    - name: Generate kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_cmd
      delegate_to: ctrl
      run_once: true
      changed_when: false
      check_mode: false

    - name: Join worker nodes to the Kubernetes cluster
      shell: " {{ join_cmd.stdout }} "
